#!/usr/bin/env bash
# Displays number 1 - 100 but something else for
# numbers that are multiples of 3 and 5, of 3 and of 5
i=1
while [ $i -le 100 ]; do
    if ((i % 15 == 0))
    then
        echo "FizzBuzz"
    elif ((i % 3 == 0))
    then
        echo "Fizz"
    elif ((i % 5 == 0))
    then
        echo "Buzz"
    else
        echo "$i"
    fi
        ((i++))
done
