#!/usr/bin/env bash
# Displays number 1 - 20 but something else after
# the 4th and 9th and 17th number
i=1
while [ $i -le 20 ]; do
    echo "$i"
    case "$i" in 
        "4")
            echo "bad luck from China"
            ;;
        "9")
            echo "bad luck from Japan"
            ;;
        "17")
            echo "bad luck from Italy"
            ;;
    esac            
    ((i++))
done
