#!/usr/bin/env bash
# script that configures an Ubuntu server with the below requirements.
# Requirements:
# - localhost resolves to 127.0.0.2
# - facebook.com resolves to 8.8.8.8.

sudo sed -i 's/127.*[localhost]$/127.0.0.2\tlocalhost' /etc/hosts
echo -e "8.8.8.8\tfacebook.com" >> //etc/hosts
