#!/usr/bin/env bash
# Run Apache on the 265-0 Docker container.
echo "ServerName localhost" >> /etc/apache2.conf
service apache2 start
FROM httpd:latest
RUN echo "Hello Holberton!" > /var/www/html/index.html
